Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/pages/home.html.erb
config/initializers/high_voltage.rb
config/routes.rb

Add high voltage and static homepage

---

app/controllers/catalog_controller.rb
app/controllers/pages_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_home_text.html.erb
app/views/catalog/_index_default.html.erb
app/views/catalog/_show_default.html.erb
config/initializers/high_voltage.rb
config/locales/blacklight.en.yml
config/routes.rb
lib/tasks/dss.rake
solr_conf/solrconfig.xml
spec/controllers/pages_controller_spec.rb

Solr auth fixes

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/select.js
app/assets/stylesheets/application.scss

Progresses #31 
Need to make sure we use `select2` as the class name for select elements to use this plugin.

Add Select2 plugin

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/layouts/application.html.erb
app/views/resources/_form.html.erb
app/views/studies/_form.html.erb
config/initializers/assets.rb
config/initializers/ckeditor.rb

Add CKEditor gem. Include toolbar in Resources and Studies textarea.

---

Gemfile.lock
app/assets/javascripts/select.js
app/assets/stylesheets/application.scss
app/controllers/catalog_controller.rb
app/helpers/blacklight_helper_behavior.rb
app/views/catalog/_home_text.html.erb
app/views/countries/_form.html.erb
app/views/countries/edit.html.erb
app/views/data_files/_form.html.erb
app/views/data_files/edit.html.erb
app/views/layouts/application.html.erb
app/views/regions/_form.html.erb
app/views/regions/edit.html.erb
app/views/resources/_form.html.erb
app/views/resources/edit.html.erb
app/views/shared/_restricted_message.html.erb
app/views/studies/_form.html.erb
app/views/studies/edit.html.erb
app/views/subjects/_form.html.erb
app/views/subjects/edit.html.erb
config/routes.rb

UI Enhancements

---

Capfile
app/controllers/catalog_controller.rb
app/controllers/studies_controller.rb
app/helpers/application_helper.rb
app/helpers/resources_helper.rb
app/models/country.rb
app/models/region.rb
app/models/study.rb
app/models/subject.rb
app/views/catalog/show.html.erb
app/views/countries/index.html.erb
app/views/data_files/show.html.erb
app/views/resources/index.html.erb
app/views/resources/show.html.erb
app/views/studies/show.html.erb
lib/tasks/dss.rake

Ui permissions cleanup

---

app/views/pages/specialists.html.erb

Changes Sociology specialist to Ofira

---

app/views/pages/computing.html.erb

@kevinreiss this is on staging: https://dss-staging.princeton.edu/computing

Updates statistic software list

---

app/views/pages/consultants.html.erb
yarn.lock

@kevinreiss This is on https://dss-staging.princeton.edu/

Updates graduate student consultants

---

app/models/resource.rb

Purge the correct ID string when a resource is deleted.

---

app/views/countries/index.html.erb

@kevinreiss this is on staging: https://dss-staging.princeton.edu/countries

Fixes countries index template

---

app/views/shared/_right-sidebar.html.erb

@kevinreiss this is on https://dss-staging.princeton.edu

Updates DSS lab consultation schedule

---

app/controllers/catalog_controller.rb

Advances pulibrary/princeton_ansible#600

updates catalog controller solr params for 7.7

---

app/views/pages/specialists.html.erb

@kevinreiss This is on https://dss-staging.princeton.edu/specialists

Update subject specialist listing

---

README.md
lib/tasks/dss.rake

Updated production indexing info.

Add production index maint. instructions.

---

app/views/pages/consultants.html.erb
app/views/shared/_right-sidebar.html.erb

This is on https://dss-staging.princeton.edu/

Updates dss lab hours and consultants

---

README.md
app/models/study.rb
app/views/studies/show.html.erb

Closes #129 at Bobray's request.

remove need to list files from dss file server.

---

app/views/studies/show.html.erb

One last template tweak for #129

Remove file table. No longer used

---

app/views/shared/_right-sidebar.html.erb

@kevinreiss changes requested by oscar

Wording changes to consultation hours

---

Gemfile.lock
config/initializers/advisory.rb

And add monkey patch to make Percona work with `rake db:migrate`

updating mysql2

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/database.yml
db/schema.rb

switching application to run with postgres

---

app/views/layouts/application.html.erb

refs https://github.com/pulibrary/princeton_ansible/pull/1441
fixes #154

Adding google analytics tags to application header

---

app/views/pages/specialists.html.erb
app/views/shared/_right-sidebar.html.erb

On https://dss-staging.princeton.edu/specialists

Updates specialists page and change current schedule highlight

---

app/views/shared/_right-sidebar.html.erb

@kevinreiss This is on staging and ok'd by Oscar

Update consultation hours

---

app/assets/stylesheets/application.scss
app/views/shared/_right-sidebar.html.erb

@kevinreiss this is on https://dss-staging.princeton.edu/ and got 👍  from dss staff

Use libcal appointments

---

app/assets/stylesheets/application.scss
app/views/shared/_right-sidebar.html.erb

@kevinreiss on https://dss-staging.princeton.edu/ with 👍  from dss staff

Add note about appt limit

---

app/models/user.rb

This speeds up progress while keeping memory use low
refs #180

Increase batch size for guest user destroy

---

config/environments/production.rb

logs are taking up all the space on the box

Reduce log level in production

---

.circleci/config.yml
config/deploy.rb
yarn.lock

Updating master to main

---

.circleci/config.yml
solr/config/_rest_managed.json
solr/config/admin-extra.html
solr/config/elevate.xml
solr/config/mapping-ISOLatin1Accent.txt
solr/config/protwords.txt
solr/config/schema.xml
solr/config/scripts.conf
solr/config/solrconfig.xml
solr/config/spellings.txt
solr/config/stopwords.txt
solr/config/stopwords_en.txt
solr/config/synonyms.txt
solr/config/xslt/example.xsl
solr/config/xslt/example_atom.xsl
solr/config/xslt/example_rss.xsl
solr/config/xslt/luke.xsl

The solr download is failing constantly, so I'm trying the way figgy does it
The config files used by ci are not really the config for DSS, but a paired down version without the stanford and umich classes refrenced.

Changing solr circle ci over to match figgy

---

app/javascript/app.vue
app/javascript/packs/application.js
app/javascript/packs/hello_vue.js
app/views/shared/_header_navbar.html.erb
config/webpack/environment.js
config/webpack/loaders/vue.js
config/webpacker.yml
package.json
yarn.lock

Updating Lux to 3

---

app/views/studies/show.html.erb
db/schema.rb
spec/views/studies/show.html.erb_spec.rb

Changing the display of a study based on the medium

---

app/views/studies/show.html.erb
spec/views/studies/show.html.erb_spec.rb

Within the show page always show the link if a folder is present
fixes #208

No longer use a check of DataFiles

---

app/views/pages/specialists.html.erb

Adding Willow

---

Gemfile.lock
app/models/user.rb
app/views/shared/_header_navbar.html.erb
config/routes.rb
spec/factories/users.rb

https://github.com/pulibrary/pul_assets/pull/78 needs to be merged before this one.
closes #172

Only use CAS authentication

---

Capfile
Gemfile
Gemfile.lock
Rakefile
config/honeybadger.yml

81 Add honeybadger

---

app/helpers/studies_helper.rb
spec/views/studies/show.html.erb_spec.rb

Studies links should be https

---

app/views/studies/show.html.erb

i269: Fix formatting on study page

---

config/environments/production.rb

260 Use action mailer config from pul-the-hard-way

---

app/models/user.rb
spec/models/user_spec.rb

Create user for CAS without password

---

db/migrate/20160808042626_create_data_files.rb

Remove duplicate column from migration

---

config/schedule.rb

Add blacklight:delete_old_searches to cron

---

app/views/layouts/application.html.erb
app/views/shared/_header_navbar.html.erb
app/views/shared/_header_navbar_noscript.html.erb
app/views/shared/_quick-links.html.erb
spec/system/home_page_spec.rb

i254: /catalog HTML should be valid

---

.circleci/config.yml
.tool-versions
package.json

Sibling PR: https://github.com/pulibrary/princeton_ansible/pull/3475
helps with #299

i299: upgrade node to 16

---

.circleci/config.yml
.rubocop.yml
app/controllers/resources_controller.rb
app/helpers/countries_helper.rb
app/views/resources/_form.html.erb
spec/helpers/countries_helper_spec.rb
spec/rails_helper.rb
spec/requests/resources_spec.rb
spec/system/resources_spec.rb

Closes #40
For an example, see https://dss-staging.princeton.edu/resources/4894

Add "All Countries" option to create and edit form

---

README.md
spec/rails_helper.rb

Default to running system specs headless

---

app/components/dss/search_bar_component.html.erb
app/controllers/catalog_controller.rb

- Re-fix render_hash_as_hidden_fields deprecation

Fix non-search param deprecation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/maintenance-task.md
.github/ISSUE_TEMPLATE/ui-change.md

- Change syntax on all labels for consistency and make it easier to extend labels in future

Add labels to bug report template

---

app/views/resources/index.html.erb

i338: prefer rails strip_tags over our custom regular expression

---

app/controllers/catalog_controller.rb
spec/system/show_page_spec.rb

i74: remove citation link

---

app/views/layouts/application.html.erb

Update google analytics with GA4 property id

---

app/views/resources/_study_details.html.erb

Change exiting to existing on edit resources page

---

README.md

@ishasinha1 and I noticed these

Add missing steps to installation docs

---

app/controllers/studies_controller.rb
app/models/study.rb
spec/requests/studies_spec.rb

Coerce study id into integer

---

app/mailers/application_mailer.rb

Update mailer config

---

app/assets/stylesheets/application.scss
app/views/shared/_quick-links.html.erb

Fix accessibility bug for quick links

---

Gemfile
Gemfile.lock

This gets us off of a pre-release.

Upgrade blacklight to 8.0.1

---

app/assets/stylesheets/application.scss
app/views/shared/_header_navbar.html.erb

Fix header alignment

---

package.json
yarn.lock

Closes #358 
Added `webpack` to `package.json` because lux required it.

Update lux and correct dependencies

---

README.md

Update README.md to include "bundle exec"

---

app/controllers/countries_controller.rb
app/controllers/regions_controller.rb
app/controllers/resources_controller.rb
app/controllers/subjects_controller.rb
app/views/countries/edit.html.erb
app/views/regions/edit.html.erb
app/views/resources/edit.html.erb
app/views/subjects/edit.html.erb
config/initializers/time_formats.rb
spec/views/countries/edit.html.erb_spec.rb
spec/views/regions/edit.html.erb_spec.rb
spec/views/resources/edit.html.erb_spec.rb
spec/views/subjects/edit.html.erb_spec.rb

Include last update date on edit pages

---

lib/tasks/admin_role.rake

include rake tasks for adding and removing admin role to users

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/controllers/countries_controller.rb
app/controllers/data_files_controller.rb
app/controllers/regions_controller.rb
app/controllers/resources_controller.rb
app/controllers/studies_controller.rb
app/controllers/subjects_controller.rb
spec/controllers/countries_controller_spec.rb
spec/controllers/data_files_controller_spec.rb
spec/controllers/regions_controller_spec.rb
spec/controllers/resources_controller_spec.rb
spec/controllers/studies_controller_spec.rb
spec/controllers/subjects_controller_spec.rb
spec/requests/resources_spec.rb
spec/system/resources_spec.rb

Connected to https://github.com/PrincetonUniversityLibrary/security/issues/71

Add before_action for authenticated admin user

---

config/deploy/staging.rb

we add a new jammy vm
we point solr to the new d cluster

point to solr-d cluster

---

app/assets/stylesheets/application.scss
app/components/blacklight/system/modal_component.html.erb
app/views/shared/_restricted_message.html.erb
package.json
yarn.lock

- update lux to v4.5.6 related to [this pull request ](https://github.com/pulibrary/approvals/pull/991)(includes steps needed for update).
part of https://github.com/pulibrary/DSS/issues/375

resolve contrast issue, update lux to v4.5.6

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Use Atkinson Hyperlegible Font

---

Gemfile
Gemfile.lock

Version 3 broke the email a record modal

Downgrade view_component to 2

---

Gemfile
Gemfile.lock
config/initializers/health_monitor.rb
config/routes.rb
spec/requests/health_check_spec.rb
spec/spec_helper.rb

Add health check

---

config/routes.rb
spec/requests/root_spec.rb

Update root redirect; remove redirects that are no longer needed.

---

Gemfile.lock

bump ckeditor to 5.1.3

---

app/views/shared/_header_navbar.html.erb

Add the abbr-name DSS to _header_navbar.html.erb

---

app/views/shared/_header_navbar.html.erb

[#472] Add Aria-label to header-navbar

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
package.json
yarn.lock

424 lux header footer

---

config/initializers/health_monitor.rb

Remove honeybadger alert for health check failures

---

app/assets/stylesheets/application.scss
app/components/blacklight/system/modal_component.html.erb

#353 scroll on countries facet

---

app/controllers/concerns/dss/catalog.rb
bearer.yml

Lookup study before redirecting

---

solr/conf/schema.xml
solr/conf/solrconfig.xml

Updated using `bundle exec rake dss:solr:update`

Refresh solr config from pul_solr

---

solr/conf/schema.xml
solr/conf/solrconfig.xml

Updated using `bundle exec rake dss:solr:update`

Refresh solr config from pul_solr again

---

app/components/blacklight/facet_field_pagination_component.html.erb
app/components/blacklight/facet_field_pagination_component.rb

Overwrite blacklight componenets and use buttons

---

app/assets/stylesheets/application.scss

Increase contrast of data files page pagination buttons

---

app/assets/stylesheets/application.scss

Increase contrast for disabled pagination buttons for accessibility

---

app/views/layouts/application.html.erb
app/views/shared/_analytics.html.erb
app/views/shared/_analytics_noscript.html.erb

This will allow us to evaluate local analytics solutions and allow AUX
to manage how analytics is done without editing all the code bases.
Work towards pulibrary/dpul-collections#709

Add google tag manager for analytics.
